# select package manager
backend: pacman
# allow to install without Internet
skip_if_no_internet: false
# update package database like "pacman -Sy" inside target system
update_db: true
# update packages inside target system
update_system: true
pacman:
# number of retries if failure happen.
    num_retries: 0
# --disable-download-timeout for pacman
    disable_download_timeout: false
# pacman --needed argument
    needed_only: true
operations:
# packages for install
- install:
    - firefox