backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
    num_retries: 1
    disable_download_timeout: false
    needed_only: false

operations:
  - try_remove:
    - mylastarch-calamares-config
    - mylastarch-system-installation
    - calamares
    - squashfs-tools
    - mkinitcpio-archiso
