<<<<<<< HEAD
=======
---
>>>>>>> 0379e5b0b645ed9c36594d417e28810bb4c992dd
efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    - file      # To swap file instead of partition
drawNestedPartitions:   false
alwaysShowPartitionLabels: true
# There are four options: erase, replace, alongside, manual),
# the default is "none".
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType:  "ext4"
<<<<<<< HEAD
availableFileSystemTypes:  ["ext4","ext3","btrfs","jfs","xfs","f2fs"]
lvm:
    enable: false
=======
availableFileSystemTypes:  ["ext4","btrfs","f2fs","xfs"]
>>>>>>> 0379e5b0b645ed9c36594d417e28810bb4c992dd
