services:
    - name: avahi-daemon
      mandatory: false

    - name: bluetooth
      mandatory: false

    - name: cronie
      mandatory: false

    - name: ModemManager
      mandatory: false

    - name: NetworkManager
      mandatory: true

    - name: cups
      mandatory: true

    - name: tlp
      mandatory: false

    - name: haveged
      mandatory: false

    - name: ufw
      mandatory: false

    - name: apparmor
      mandatory: false

    - name: snapd.apparmor
      mandatory: false

    - name: snapd
      mandatory: false

    - name: fstrim.timer
      mandatory: false

    - name: pkgfile-update.timer
      mandatory: false

    - name: sddm
      mandatory: true

targets:
    - name: "graphical"
      mandatory: true

disable:
    - name: pacman-init
      mandatory: false
