---
dontChroot: false

script:
  - "sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck)/' /etc/mkinitcpio.conf"
  - "grep -qxF 'HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block filesystems fsck)' /etc/mkinitcpio.conf"
  - command: "/usr/local/bin/mylastarch-before"

i18n:
  name: "Preparing your system for MY LAST ARCH"

timeout: 999
