---
dontChroot: false

script:
  - "-rm -f ${ROOT}/etc/systemd/system/multi-user.target.wants/pacman-init.service"
  - "-rm -f ${ROOT}/etc/systemd/system/pacman-init.service"
  - "-rm -f ${ROOT}/home/*/calamares.desktop"
  - "-rm -f ${ROOT}/home/*/Desktop/calamares.desktop"
  - "-rm -f ${ROOT}/home/*/import-mylastarch-key.sh"
  - "-rm -f ${ROOT}/etc/sddm.conf.d/autologin.conf"
  - command: "/usr/local/bin/mylastarch-final"

i18n:
  name: "Preparing your system for MY LAST ARCH"

timeout: 999
