defaultGroups:
    - lp
    - network
    - power
    - sys
    - wheel
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: false
availableShells: /bin/bash, /bin/zsh
avatarFilePath:  ~/.face
userShell:       /bin/bash

passwordRequirements:
    nonempty: true
    minLength: 1
    maxLength: -1
    allowWeakPasswords: true
    allowWeakPasswordsDefault: true
