showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    10
    requiredRam:        1.0
    internetCheckUrl:   http://google.com
check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen

required:
        - storage
        - ram

#geoip:
#    style:    "fixed"
#    url:      "https://geoip.kde.org/v1/ubiuity"
#    selector: "CountryCode" # leave blank for the default
 geoip:
    style:    "none"
    url:      "https://geoip.kde.org/v1/ubiuity"
    selector: "CountryCode" # leave blank for the default
   

