modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs1.conf
- id:       before
  module:   shellprocess
  config:   shellprocess-before.conf
- id:       final
  module:   shellprocess
  config:   shellprocess-final.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - initcpio
  - unpackfs@rootfs
  - locale
  - keyboard
  - networkcfg
  - shellprocess@before
  - users
  - removeuser
  - displaymanager
  - packages
  - bootloader
  - shellprocess@final
  - preservefiles
  - umount
- show:
  - finished

branding: default
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
